version: 2
jobs:
  build:
    
    working_directory: ~/spring-boot-rest-services-with-unit-and-integration-tests

    docker:
      - image: circleci/openjdk:8-jdk-browsers
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    steps:

      - checkout

      - restore_cache:
          key: spring-boot-rest-services-with-unit-and-integration-tests-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: spring-boot-rest-services-with-unit-and-integration-tests-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/spring-boot-rest-services-with-unit-and-integration-tests-0.0.1-SNAPSHOT.jar

      - run: mvn sonar:sonar   -Dsonar.projectKey=cyyeong_spring-boot-rest-services-with-unit-and-integration-tests  -Dsonar.organization=cyyeong-github    -Dsonar.host.url=https://sonarcloud.io    -Dsonar.login=d4b9d456a23a92ca358e7e5de0b3c2a17f5ad6c9